ngmix/bootstrap.py, ngmix/fitting.py
Here are all of the changes. I have tucked some cosmetic changes in as well. You will need the changes in gmix_meds as well.
=> asinh isamp

ngmix/bootstrap.py
more small changes needed for ngmixer - needed to do PSF fits like the old gmix_meds repo
=> pass pars and guesses to psf fitter

ngmix/jacobian.py
I remember finding this and telling you about it. However, I apparently forgot to submit a PR for the fix. Here it is...
=> bug in jacobian

ngmix/bootstrap.py, ngmix/fitting.py
I also fixed bug in passing keywords to the bootstrappers.
=> changes to allow for psfex psf normalization

ngmix/_gmix.c, ngmix/gmix.py
=> Revert "added rendering with fast exp function"

ngmix/_gmix.c, ngmix/_gmix.h, ngmix/bootstrap.py, ngmix/btest.py, ngmix/em.py, ngmix/fitting.py, ngmix/gmix.py, ngmix/jacobian.py, ngmix/metacal.py, ngmix/observation.py, ngmix/priors.py, ngmix/test.py
=> Metacalwcs

ngmix/medsreaders.py
The ngmix rmeds reader was not grabbing the noise image if it is in the file.
=> BUG make sure to add the noise obs

ngmix/__init__.py, ngmix/gaussap.py
=> adding gauss ap code

ngmix/medsreaders.py
=> add file_path to metadata

ngmix/tests/test_pixels.py
This PR adds tests for the pixels and coords arrays.
=> TST added tests for pixels and coord arrays

CHANGES.md
This PR updates the changelog. @esheldon should confirm I got the order of events right.
=> DOC update changelog

ngmix/bootstrap.py, ngmix/gmix.py
this seems to fit DES deep field psfs quite well
=> implement 5 gauss em guess for psfs

CHANGES.md, ngmix/__init__.py, ngmix/gaussmom.py, ngmix/tests/test_gaussmom.py
This PR adds a Gaussian moments fitter.
Closes #85
=> ENH add gaussian moments fitter

ngmix/gmix.py
also be smarter about order of computation
=> record flux error in weighted moms

ngmix/bootstrap.py, ngmix/gmix.py
I accidentally added multiple different things into one commit.
In addition to higher ngauss coellip models, also added sending a guess to the psf runners
=> PSF fitting features

ngmix/observation.py, ngmix/tests/test_observation.py
=> add option to Observation to not store pixels

.ci_scripts/install_miniconda.sh, .flake8, .travis.yml, CHANGES.md, ngmix/shape.py, ngmix/tests/test_shape.py, setup.py
=> ENH docs and tests for shape module

CHANGES.md, ngmix/moments.py, ngmix/tests/test_moments.py
This PR has tests for moments.
=> TST tests for moments

CHANGES.md, ngmix/jacobian.py, ngmix/tests/test_jacobian.py
This PR finishes some tests of the jacobians.
=> TST finish jacobian tests

.coveragerc, CHANGES.md, ngmix/observation.py, ngmix/tests/test_kobs.py, ngmix/tests/test_make_kobs.py, ngmix/tests/test_multibandobslist.py, ngmix/tests/test_observation.py, ngmix/tests/test_obslist.py
This PR catches some edge cases missed in the current tests.
Many of the tests here are simple sanity checks. We have or will have functional tests in the fitting routines which depend on much of the functionality in the classes here.
=> TST added tests for observations

ngmix/medsreaders.py
the factor which converted from the default zp in electrons
to 30
=> record scale factor for image

CHANGES.md, ngmix/gexceptions.py, ngmix/tests/test_gexceptions.py
This PR adds a base class and some tests for the exceptions.
=> TST added simple tests for exception inheritance and behaviors

ngmix/priors/priors.py, ngmix/tests/test_priors_simple.py
This PR adds more docs and tests for the priors module.
=> TST added more tests for priors module

ngmix/fitting.py
This PR starts in on using logging in the fitting module.
=> REF use logging

CHANGES.md, ngmix/priors/__init__.py, ngmix/priors/kde.py, ngmix/priors/multivariate.py, ngmix/priors/priors.py, ngmix/priors/shape.py, ngmix/tests/test_priors2d.py, ngmix/tests/test_priors_shear.py, ngmix/tests/test_priors_simple.py
This PR continues writing tests for priors.
=> ENH tests for priors, removed some, bug fixes, documentation

examples/metacal/metacal.py, examples/metacal/metacal_select.py, ngmix/metacal_bootstrap.py, ngmix/tests/test_metacal_bootstrap.py
return the metacal obsdict for the metacal bootstrapper
=> Mcal obsdict

examples/metacal/metacal.py, examples/metacal/metacal_select.py, ngmix/metacal.py
Cleaning up the code for more code re-use
Doing some cacheing for speedup
Considering making a metacal sub-package
=> Metacal cleanup and speed

ngmix/tests/test_gaussap.py
=> test gaussap fluxes

.github/workflows/test.yml, ngmix/tests/_fakemeds.py, ngmix/tests/test_medsreaders.py
For now the test is skipped unless an environment var is set `MEDS_TEST_FILE`
=> Medsreader tests

ngmix/tests/_fakemeds.py
was not fully testing the meds readers due to bugs filling in parts of the object data, resulting in a lack of diversity in the object data
=> bugs not filling out object_data with diversity

CHANGES.md, ngmix/medsreaders.py, ngmix/observation.py, ngmix/tests/_fakemeds.py, ngmix/tests/test_medsreaders.py, ngmix/tests/test_observation.py
This PR adds the mfrac attribute and tests for it.
=> ENH add mfrac attribute and meds support

CHANGES.md, README.md, ngmix/_version.py
=> getting ready for 2.0.0

CHANGES.md, ngmix/metacal/metacal.py, ngmix/tests/test_metacal_bootstrap.py
=> BUG fix double convolution of pixel in metacal

.github/workflows/mdet.yml, mdet_tests/test_mdet_regression.py
This PR fixes the regression tests.
=> TST run regression tests against 1.3.9

CHANGES.md
This PR updates the changelog for v1.3.9.
=> DOC update changelog for v1.3.9

CHANGES.md, ngmix/guessers.py
=> Infinite recursion in psf guesser

.github/workflows/mdet.yml, CHANGES.md, ngmix/admom/admom.py, ngmix/tests/test_admom.py
This PR fixes the admom flux to match the normalization of the other moments codes. 
closes #193
=> BUG fix admom flux

CHANGES.md, ngmix/tests/test_util.py, ngmix/util.py
=> make get_ratio_error and get_ratio_var support arrays

CHANGES.md, ngmix/gmix/gmix.py, ngmix/tests/test_gmix.py
=> Add ability to concatenate gmixes

CHANGES.md, ngmix/admom/admom.py
This PR adds sums norm to admom.
=> ENH add sums_norm to admom

CHANGES.md
Just fixing the changelog before tagging
=> update changelog final for 2.3.2
