- ngmix/em.py
- ngmix/fitting.py
I have added the approximate EM solver w/ PSF deconvolution to ngmix. This should hopefully be useful for seeding parameters. I have found that doing this with a final LM step to finish the fit is not so bad for quick and robustly getting the ML point, at least in simulations. You will need to install beckermr/emshear in order to use the new code. In beckermr/emshear I have done a fair bit of optimization moving the most expensive parts into C. There is a test script in the emshear repo which runs a test a problem.
I also added a go alias to LMSimple.
> added approximate EM solver

- ngmix/bootstrap.py
This is a simple change to store the fitter for each PSF observation when running the bootstrapper.
> keep psf fitter for each obs

- setup.py
This is the same error that we decided to fix in fitsio, where include_dirs needs to be fed to the extensions, not the setup call.
> moved include dirs

- ngmix/_gmix.c
- ngmix/guessers.py
I have put in some changes to fix floating point errors.
1. In the `C`, for cmodel fits sometimes the `T` normalization can diverge so it checks if `T` is zero anyways and if so, just sets the internal `T` to zero.
2. In the python layer, I made the guessers check before taking logs of negative or zero `T`'s or fluxes. I am clipping the values at `1e-10`. This change may have side effects.
> floating point errors

- ngmix/_gmix.c
- ngmix/gmix.py
This has been fully tested. Here is the code I used to test the functions
```python
#!/usr/bin/env python
import numpy as np
import time
import ngmix
dim=64
jac = ngmix.UnitJacobian(dim/2+1,dim/2+1)
pars = [0.0, 0.0, 0.2, -0.1, 32.0, 100.0]
gmix = ngmix.GMixModel(pars,"exp")
dims=[dim,dim]
ntry = 10
for ns in [1,3,5,10]:
for npts in [None,5,10]:
for jc in [jac,None]:
for FE in [False,True]:
t0 = time.time()
for i in xrange(ntry):
image = gmix.make_image(dims,jacobian=jc,fast_exp=FE,
nsub=ns,npoints=npts)
tjac = time.time() - t0
if FE:
print "fast exp:",tjac
else:
print "std exp: ",tjac
if FE:
imfe = image
else:
im = image
print "max abs diff:",np.max(np.abs(imfe-im))
```
> added rendering with fast exp function

- .gitignore
- ngmix/meds.py
- ngmix/medsreaders.py
This PR has MEDS readers subclassed to output ngmix observations. I think this is the right spot for them as opposed to the MEDS repo (i.e., if you need the ngmix stuff, then you have ngmix installed).
> ENH add meds readers for ngmix obs

- ngmix/gmix.py
This PR attempts to solve 3 issues related to Balrog:
1. The T-clipping added in 310d7a6b7c60aeca2e17e975d47c15ad49ff5a53 to `make_galsim_object()` does not actually avoid GalSim rendering failures.
2. The default clipping of `Tmin=0.001` is too large.
3. There is no existing way to pass `gsparams` to the created `GSObject`.
The problem with (1) is that the size clipping is done on `Tround` rather than the individual Gaussian `T`s. This is an issue for `TdByTe=0` objects which store zero values for the covariance matrix; e.g.
```
p: 0.09917 row: 0 col: 0 irr: -1.087e-05 irc: 3.355e-08 icc: -1.107e-05
p: 1.279 row: 0 col: 0 irr: -7.994e-05 irc: 2.468e-07 icc: -8.141e-05
p: 8.577 row: 0 col: 0 irr: -0.0003499 irc: 1.08e-06 icc: -0.0003564
p: 35.09 row: 0 col: 0 irr: -0.001195 irc: 3.69e-06 …
```
> GalSim rendering T-clip fix and passing `gsparams`

- ngmix/medsreaders.py
so we can over-ride it in subclasses, e.g. the one in fitvd
where we are reading from a psfex obj
> use method to get psf cen

- ngmix/gmix.py
> Fixed `pars` definition typo in `GMixBDF` docstring.

- ngmix/em.py
- ngmix/observation.py
- ngmix/tests/test_observation.py
added constructor option to Observation about ignoring the zero weight pixels
default is still to ignore, but on can now specify `ignore_zero_weight=False`.
Added a test.
Also threw in returning the correct sky in em.prep_sky
> Update pixels zero

- examples/em/em_1gauss.py
- examples/em/em_2gauss.py
- examples/em/em_2gauss_psf.py
- examples/metacal/metacal.py
- examples/metacal/metacal_select.py
- ngmix/__init__.py
- ngmix/admom.py
- ngmix/bootstrap.py
- ngmix/em.py
- ngmix/fitting.py
- ngmix/galsimfit.py
- ngmix/gaussmom.py
- ngmix/guessers.py
- ngmix/joint_prior.py
- ngmix/metacal/bootstrap.py
- ngmix/metacal/metacal.py
- ngmix/runners.py
- ngmix/tests/_priors.py
- ngmix/tests/test_admom.py
- ngmix/tests/test_bootstrap.py
- ngmix/tests/test_em.py
- ngmix/tests/test_gaussmom.py
- ngmix/tests/test_metacal_bootstrap.py
- ngmix/tests/test_ml_fitting_exp_obj_gauss_psf.py
- ngmix/tests/test_ml_fitting_galsim.py
- ngmix/tests/test_ml_fitting_gauss.py
- ngmix/tests/test_psf_runners.py
- ngmix/tests/test_runners.py
- ngmix/tests/test_template_flux.py
This was suggested by @beckermr 
TODO
> fitters/runners/bootstrappers return FitModel/Result objects

- CHANGES.md
- mdet_tests/test_mdet_regression.py
- ngmix/admom.py
- ngmix/em.py
- ngmix/gaussmom.py
- ngmix/gmix_nb.py
- ngmix/guessers.py
- ngmix/jacobian.py
- ngmix/jacobian_nb.py
- ngmix/pixels.py
- ngmix/pixels_nb.py
- ngmix/tests/test_bootstrap.py
- ngmix/tests/test_gmix.py
- ngmix/tests/test_jacobian.py
- ngmix/tests/test_ml_fitting_exp_obj_gauss_psf.py
- ngmix/tests/test_ml_fitting_gauss.py
- ngmix/tests/test_pixels.py
- ngmix/tests/test_template_flux.py
closes #95 
This is a big, breaking change.
The pixel area is carried through a number of calculations now such that the units are in flux, like galsim.  However, no integration of pixels is performed.
> Flux units

- CHANGES.md
- mdet_tests/test_mdet_regression.py
- ngmix/__init__.py
- ngmix/_version.py
- ngmix/observation.py
- ngmix/tests/test_observation.py
- setup.py
This PR 
- allows store pixels and ignore zero weight to be changed for observations
- propagates these values when observations are copied (breaking API change)
- moves the version to be stored in one spot
- bumps the version to 2.0.0rc2
- put manual flux scaling in mdet regression tests
> ENH allow store pixels and ignore zero weight to be set

- CHANGES.md
- ngmix/__init__.py
- ngmix/metacal.py
- setup.py
This PR fixes the same bug reported in #160 but for the 1.3.x series. I am merging it into a 1.3.x release branch we can use to release 1.3.9 with the fix.
> BUG fix rendering bug in metacal; bump to 1.3.9

- CHANGES.md
- ngmix/metacal/metacal.py
- ngmix/tests/test_metacal.py
fix bug where sheared psf was not cached properly
was only caching based on |g|
> Metacal psf cache bug

- CHANGES.md
- ngmix/_version.py
- ngmix/admom/admom.py
- ngmix/admom/admom_nb.py
- ngmix/tests/test_admom.py
closes #180 
Adds option for adaptive moments `cenonly=True` to only vary the center.  Adds new function `ngmix.admom.find_cen_admom`
> Add option to fit center only in adaptive moments

- CHANGES.md
- ngmix/metacal/metacal.py
In MetacalFitGaussPSF when using adaptive moments to get the psf
model, be careful to use the fitted parameters rather than going
through an intermediate gmix, which converts e1, e2 to g1, g2 and
can fail in rare cases.
> BUG fix buggy admom usage in metacal

- CHANGES.md
- ngmix/metacal/convenience.py
- ngmix/metacal/metacal.py
- ngmix/tests/test_metacal.py
closes #172 
It is no longer required to send a random number generator
to the constructors for MetacalGaussPSF and MetacalAnalyticPSF.  If one
is sent it is still used to add a small amount of noise.
> No longer require rng forMetacalGaussPSF and MetacalAnalyticPSF

- CHANGES.md
- ngmix/admom/admom.py
- ngmix/tests/test_admom.py
It appears that I messed up the flags in the recent admom change. I also found a better way to match the flux normalization. The old way threw errors sometimes for reasons I did not follow.
> BUG missing flags; better flux norm

- CHANGES.md
- ngmix/metacal/metacal.py
closes #204 
This passes along all the supported attributes
> metacal codes use a copy() of the input obs

- CHANGES.md
- ngmix/prepsfmom.py
- ngmix/tests/test_prepsfmom.py
This PR adds apodization for the pre-PSF moments and tests that it does the right thing.
> ENH apodize the pre-PSF moments

- CHANGES.md
- ngmix/_version.py
- ngmix/prepsfmom.py
- ngmix/tests/test_prepsfmom.py
This PR sets the kind attribute for the prePSFMom fitter.
> BUG add kind attribute for PrePSFMom fitter

- mdet_tests/test_mdet_regression.py
- ngmix/jacobian/jacobian.py
- ngmix/metacal/metacal.py
- ngmix/prepsfmom.py
- ngmix/tests/_galsim_sims.py
- ngmix/tests/test_metacal_cache.py
- ngmix/tests/test_prepsfmom.py
This PR adds caching of FFTs of various images in order to speed up the code.
> PERF cache FFTs of various quantities

- CHANGES.md
- ngmix/gaussmom.py
This PR changes GaussMom to use the 1/area normalization consistently everywhere in its outputs.
> BUG use area norm for all gauss mom things

- CHANGES.md
- mdet_tests/test_mdet_regression.py
- ngmix/gaussmom.py
- ngmix/gmix/gmix.py
- ngmix/moments.py
- ngmix/prepsfmom.py
- ngmix/tests/test_prepsfmom.py
This PR adds the overall moment weight function normalization to fix a bug in mdet where this is ignored when combining shapes.
To do:
> ENH add moment weight sums to output

- CHANGES.md
- ngmix/prepsfmom.py
- ngmix/tests/test_prepsfmom.py
I missed testing this branch of the code and it had a bug.
> BUG non-scalar norm in sums_norm for prepsf moments

- CHANGES.md
- ngmix/moments.py
- ngmix/tests/test_moments.py
This PR adds a function to regularize moments results.
> ENH added regularization function for moments

- CHANGES.md
- ngmix/_version.py
- ngmix/prepsfmom.py
- ngmix/tests/test_leastsqbound.py
- ngmix/tests/test_prepsfmom.py
Trying some stuff here after talking with Mike.
> PERF add O(N) phase shift computation

- CHANGES.md
- ngmix/__init__.py
- ngmix/_version.py
- ngmix/guessers.py
- ngmix/tests/test_guessers.py
> add guesser for BDF with psf flux

- .github/workflows/test.yml
- CHANGES.md
- ngmix/_version.py
- ngmix/metacal/metacal.py
- ngmix/prepsfmom.py
- ngmix/tests/conftest.py
- ngmix/tests/test_metacal.py
- ngmix/tests/test_metacal_bootstrap.py
- ngmix/tests/test_metacal_cache.py
- ngmix/tests/test_metacal_noise_image.py
- ngmix/tests/test_prepsfmom.py
I've seen increased memory use due to caching which is expected. This PR turns it off by default since it is really useful only for certain things and adds apis to turn it back on as needed.
> ENH make caching optional

- CHANGES.md
- ngmix/prepsfmom.py
- ngmix/tests/test_prepsfmom.py
This PR adds a pixel deconvolution for PSFs only when running prePSF moments. This feature makes the PSF moments consistent with object ones in that the pixel is removed.
> ENH deconvolve pixel in prepsf moments

- CHANGES.md
- mdet_tests/test_mdet_regression.py
- ngmix/_version.py
- ngmix/metacal/metacal.py
- ngmix/observation.py
- ngmix/tests/test_metacal_accuracy.py
- ngmix/tests/test_metacal_bootstrap.py
The psf determination was being done on the pre pixel rather than post pixel psf.  This required a Convolve with the pixel afterward, which does not work as expected when the wcs is complex
Added a metacal accuracy test as well
> fix bug with metacal psf method "gauss"

- .coveragerc
- .github/workflows/mdet.yml
- .github/workflows/test.yml
- CHANGES.md
- ngmix/admom/admom.py
- ngmix/admom/admom_nb.py
- ngmix/fitting/leastsqbound.py
- ngmix/gmix/gmix_nb.py
- ngmix/tests/_fakemeds.py
- ngmix/tests/test_admom.py
- ngmix/tests/test_em.py
- ngmix/tests/test_leastsqbound.py
- ngmix/tests/test_metacal_accuracy.py
- ngmix/tests/test_prepsfmom.py
- ngmix/tests/test_util.py
closes #240 
Add some docs as well and remove unused
entry in admom dtype
> add rho4 to adaptive moments

- CHANGES.md
- ngmix/_version.py
- ngmix/guessers.py
- ngmix/tests/_sims.py
- ngmix/tests/test_guessers.py
fix bug when moms give a bad size for guesser and using a random number
generator that checks low/high such as (np.random.default_rng)
> Guesser fix

- CHANGES.md
- ngmix/gaussmom.py
- ngmix/gmix/gmix.py
- ngmix/gmix/gmix_nb.py
- ngmix/moments.py
- ngmix/tests/test_gaussmom.py
- ngmix/tests/test_gmix.py
These are part of the sums/sums_cov arrays returned by gmix.get_weighted_moments when `with_higher_order=True` is sent.
This is also available with `GaussMom(fwhm, with_higher_order=True)`
Currently the sums are calculated and are stored in a larger "sums" and "sums_cov" arrays in the results.  No normalized moments are returned.
Names and indices for moments can be found in moments.MOMENTS_NAME_MAP
> Add optional higher order moments

- ngmix/moments.py
- ngmix/tests/test_gmix.py
Add normalized moments by name, such as M20 which is the M20 sums divided by the flux sums
Also add uncertainties
Higher order moments will be included only if present
Since the only failure mode for these is flux < 0, we don't store flags. We instead store the number as nan
> add normalized moments and moment errors by name
